# TCL File Generated by Component Editor 13.0sp1
# Thu Mar 26 11:16:02 CET 2015
# DO NOT MODIFY


# 
# LDC1000 "LDC1000" v0.1.0
# NTB (ch.ntb.inf) 2015.03.26.11:16:02
# Interface for LDC1000 Sensor 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module LDC1000
# 
set_module_property DESCRIPTION "Interface for LDC1000 Sensor "
set_module_property NAME LDC1000
set_module_property VERSION 0.1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "fLink/Sensor"
set_module_property AUTHOR "NTB (ch.ntb.inf)"
set_module_property DISPLAY_NAME LDC1000
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ldc1000_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ldc1000_interface.m.vhd VHDL PATH ldc1000_interface.m.vhd TOP_LEVEL_FILE
add_fileset_file spi_master.m.vhd VHDL PATH ../../../../functionalBlocks/spi_master/src/spi_master.m.vhd
add_fileset_file ldc1000.m.vhd VHDL PATH ../../../../functionalBlocks/ldc1000/src/ldc1000.m.vhd
add_fileset_file flink_definitions.vhd VHDL PATH ../../../../fLink/core/flink_definitions.vhd
add_fileset_file adjustable_pwm.m.vhd VHDL PATH ../../../../functionalBlocks/adjustable_pwm/src/adjustable_pwm.m.vhd


# 
# parameters
# 
add_parameter BASE_CLK INTEGER 250000000
set_parameter_property BASE_CLK DEFAULT_VALUE 250000000
set_parameter_property BASE_CLK DISPLAY_NAME BASE_CLK
set_parameter_property BASE_CLK TYPE INTEGER
set_parameter_property BASE_CLK UNITS None
set_parameter_property BASE_CLK ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BASE_CLK HDL_PARAMETER true
add_parameter SCLK_FREQUENCY INTEGER 4000000
set_parameter_property SCLK_FREQUENCY DEFAULT_VALUE 4000000
set_parameter_property SCLK_FREQUENCY DISPLAY_NAME SCLK_FREQUENCY
set_parameter_property SCLK_FREQUENCY TYPE INTEGER
set_parameter_property SCLK_FREQUENCY UNITS None
set_parameter_property SCLK_FREQUENCY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SCLK_FREQUENCY HDL_PARAMETER true
add_parameter UNIQUE_ID STD_LOGIC_VECTOR 0
set_parameter_property UNIQUE_ID DEFAULT_VALUE 0
set_parameter_property UNIQUE_ID DISPLAY_NAME UNIQUE_ID
set_parameter_property UNIQUE_ID TYPE STD_LOGIC_VECTOR
set_parameter_property UNIQUE_ID UNITS None
set_parameter_property UNIQUE_ID ALLOWED_RANGES 0:4294967295
set_parameter_property UNIQUE_ID HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 oslv_avs_read_data readdata Output 32
add_interface_port avalon_slave_0 islv_avs_address address Input 4
add_interface_port avalon_slave_0 isl_avs_read read Input 1
add_interface_port avalon_slave_0 isl_avs_write write Input 1
add_interface_port avalon_slave_0 islv_avs_write_data writedata Input 32
add_interface_port avalon_slave_0 islv_avs_byteenable byteenable Input 4
add_interface_port avalon_slave_0 osl_avs_waitrequest waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink isl_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink isl_reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end osl_sclk export Output 1
add_interface_port conduit_end oslv_csb export Output 1
add_interface_port conduit_end osl_sdi export Output 1
add_interface_port conduit_end osl_tbclk export Output 1
add_interface_port conduit_end isl_sdo export Input 1

