# TCL File Generated by Component Editor 13.0sp1
# Tue Apr 19 14:31:08 CEST 2016
# DO NOT MODIFY


# 
# fqd_device "FQD Device" v1.0
#  2016.04.19.14:31:08
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module fqd_device
# 
set_module_property DESCRIPTION ""
set_module_property NAME fqd_device
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP fLink/axi/subDevices
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "FQD Device"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fqd_device
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file fqd_device.m.vhd VHDL PATH fqd_device.m.vhd TOP_LEVEL_FILE
add_fileset_file axi_slave.m.vhd VHDL PATH ../../axiSlave/src/axi_slave.m.vhd
add_fileset_file flink_definitions.vhd VHDL PATH ../../../../fLink/core/flink_definitions.vhd
add_fileset_file fqd.m.vhd VHDL PATH ../../../../functionalBlocks/fqd/src/fqd.m.vhd


# 
# parameters
# 
add_parameter number_of_fqds INTEGER 1
set_parameter_property number_of_fqds DEFAULT_VALUE 1
set_parameter_property number_of_fqds DISPLAY_NAME number_of_fqds
set_parameter_property number_of_fqds TYPE INTEGER
set_parameter_property number_of_fqds UNITS None
set_parameter_property number_of_fqds ALLOWED_RANGES -2147483648:2147483647
set_parameter_property number_of_fqds HDL_PARAMETER true
add_parameter unique_id STD_LOGIC_VECTOR 0
set_parameter_property unique_id DEFAULT_VALUE 0
set_parameter_property unique_id DISPLAY_NAME unique_id
set_parameter_property unique_id TYPE STD_LOGIC_VECTOR
set_parameter_property unique_id UNITS None
set_parameter_property unique_id ALLOWED_RANGES 0:4294967295
set_parameter_property unique_id HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink axi_aclk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink axi_areset_n reset_n Input 1


# 
# connection point altera_axi4_slave
# 
add_interface altera_axi4_slave axi4 end
set_interface_property altera_axi4_slave associatedClock clock_sink
set_interface_property altera_axi4_slave associatedReset reset_sink
set_interface_property altera_axi4_slave readAcceptanceCapability 1
set_interface_property altera_axi4_slave writeAcceptanceCapability 1
set_interface_property altera_axi4_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4_slave readDataReorderingDepth 1
set_interface_property altera_axi4_slave bridgesToMaster ""
set_interface_property altera_axi4_slave ENABLED true
set_interface_property altera_axi4_slave EXPORT_OF ""
set_interface_property altera_axi4_slave PORT_NAME_MAP ""
set_interface_property altera_axi4_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4_slave axi_awaddr awaddr Input 7
add_interface_port altera_axi4_slave axi_awlen awlen Input 8
add_interface_port altera_axi4_slave axi_awsize awsize Input 3
add_interface_port altera_axi4_slave axi_awburst awburst Input 2
add_interface_port altera_axi4_slave axi_awvalid awvalid Input 1
add_interface_port altera_axi4_slave axi_awready awready Output 1
add_interface_port altera_axi4_slave axi_wdata wdata Input 32
add_interface_port altera_axi4_slave axi_wstrb wstrb Input 4
add_interface_port altera_axi4_slave axi_wvalid wvalid Input 1
add_interface_port altera_axi4_slave axi_wready wready Output 1
add_interface_port altera_axi4_slave axi_araddr araddr Input 7
add_interface_port altera_axi4_slave axi_arvalid arvalid Input 1
add_interface_port altera_axi4_slave axi_arready arready Output 1
add_interface_port altera_axi4_slave axi_arid arid Input 1
add_interface_port altera_axi4_slave axi_arlen arlen Input 8
add_interface_port altera_axi4_slave axi_arsize arsize Input 3
add_interface_port altera_axi4_slave axi_arburst arburst Input 2
add_interface_port altera_axi4_slave axi_rdata rdata Output 32
add_interface_port altera_axi4_slave axi_rresp rresp Output 2
add_interface_port altera_axi4_slave axi_rvalid rvalid Output 1
add_interface_port altera_axi4_slave axi_rready rready Input 1
add_interface_port altera_axi4_slave axi_rid rid Output 1
add_interface_port altera_axi4_slave axi_rlast rlast Output 1
add_interface_port altera_axi4_slave axi_bresp bresp Output 2
add_interface_port altera_axi4_slave axi_bvalid bvalid Output 1
add_interface_port altera_axi4_slave axi_bready bready Input 1
add_interface_port altera_axi4_slave axi_bid bid Output 1
add_interface_port altera_axi4_slave axi_awid awid Input 1


# 
# connection point enc_a
# 
add_interface enc_a conduit end
set_interface_property enc_a associatedClock clock_sink
set_interface_property enc_a associatedReset reset_sink
set_interface_property enc_a ENABLED true
set_interface_property enc_a EXPORT_OF ""
set_interface_property enc_a PORT_NAME_MAP ""
set_interface_property enc_a SVD_ADDRESS_GROUP ""

add_interface_port enc_a islv_enc_A export Input number_of_fqds


# 
# connection point enc_b
# 
add_interface enc_b conduit end
set_interface_property enc_b associatedClock clock_sink
set_interface_property enc_b associatedReset reset_sink
set_interface_property enc_b ENABLED true
set_interface_property enc_b EXPORT_OF ""
set_interface_property enc_b PORT_NAME_MAP ""
set_interface_property enc_b SVD_ADDRESS_GROUP ""

add_interface_port enc_b islv_enc_B export Input number_of_fqds

