# TCL File Generated by Component Editor 13.0sp1
# Fri May 27 14:30:31 CEST 2016
# DO NOT MODIFY


# 
# ppwa_device "ppwa Device" v1.0
#  2016.05.27.14:30:31
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module ppwa_device
# 
set_module_property DESCRIPTION ""
set_module_property NAME ppwa_device
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP fLink/axi/subDevices
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "ppwa Device"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ppwaDevice_v1_0
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ppwa.m.vhd VHDL PATH ../../../../functionalBlocks/ppwa/src/ppwa.m.vhd
add_fileset_file flink_definitions.vhd VHDL PATH ../../../../fLink/core/flink_definitions.vhd
add_fileset_file ppwaDevice_v1_0.vhd VHDL PATH vivadoIPPackage/ppwaDevice_1.0/hdl/ppwaDevice_v1_0.vhd TOP_LEVEL_FILE
add_fileset_file ppwaDevice_v1_0_S00_AXI.vhd VHDL PATH vivadoIPPackage/ppwaDevice_1.0/hdl/ppwaDevice_v1_0_S00_AXI.vhd


# 
# parameters
# 
add_parameter unique_id STD_LOGIC_VECTOR 0 "Unique ID"
set_parameter_property unique_id DEFAULT_VALUE 0
set_parameter_property unique_id DISPLAY_NAME unique_id
set_parameter_property unique_id WIDTH 32
set_parameter_property unique_id TYPE STD_LOGIC_VECTOR
set_parameter_property unique_id UNITS None
set_parameter_property unique_id ALLOWED_RANGES 0:4294967295
set_parameter_property unique_id DESCRIPTION "Unique ID"
set_parameter_property unique_id HDL_PARAMETER true
add_parameter number_of_ppwas INTEGER 1 "Number of ppwas which will be generated"
set_parameter_property number_of_ppwas DEFAULT_VALUE 1
set_parameter_property number_of_ppwas DISPLAY_NAME number_of_ppwas
set_parameter_property number_of_ppwas TYPE INTEGER
set_parameter_property number_of_ppwas UNITS None
set_parameter_property number_of_ppwas ALLOWED_RANGES -2147483648:2147483647
set_parameter_property number_of_ppwas DESCRIPTION "Number of ppwas which will be generated"
set_parameter_property number_of_ppwas HDL_PARAMETER true
add_parameter base_clk INTEGER 125000000 "Clock frequency which is used on the clock input signal of this block"
set_parameter_property base_clk DEFAULT_VALUE 125000000
set_parameter_property base_clk DISPLAY_NAME base_clk
set_parameter_property base_clk TYPE INTEGER
set_parameter_property base_clk UNITS None
set_parameter_property base_clk ALLOWED_RANGES -2147483648:2147483647
set_parameter_property base_clk DESCRIPTION "Clock frequency which is used on the clock input signal of this block"
set_parameter_property base_clk HDL_PARAMETER true
add_parameter C_S00_AXI_ID_WIDTH INTEGER 1
set_parameter_property C_S00_AXI_ID_WIDTH DEFAULT_VALUE 1
set_parameter_property C_S00_AXI_ID_WIDTH DISPLAY_NAME C_S00_AXI_ID_WIDTH
set_parameter_property C_S00_AXI_ID_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_ID_WIDTH UNITS None
set_parameter_property C_S00_AXI_ID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_ID_WIDTH HDL_PARAMETER true
add_parameter C_S00_AXI_DATA_WIDTH INTEGER 32
set_parameter_property C_S00_AXI_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property C_S00_AXI_DATA_WIDTH DISPLAY_NAME C_S00_AXI_DATA_WIDTH
set_parameter_property C_S00_AXI_DATA_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_DATA_WIDTH UNITS None
set_parameter_property C_S00_AXI_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_DATA_WIDTH HDL_PARAMETER true
add_parameter C_S00_AXI_ADDR_WIDTH INTEGER 12 ""
set_parameter_property C_S00_AXI_ADDR_WIDTH DEFAULT_VALUE 12
set_parameter_property C_S00_AXI_ADDR_WIDTH DISPLAY_NAME C_S00_AXI_ADDR_WIDTH
set_parameter_property C_S00_AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_ADDR_WIDTH UNITS None
set_parameter_property C_S00_AXI_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_ADDR_WIDTH DESCRIPTION ""
set_parameter_property C_S00_AXI_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point conduit_end_1
# 
add_interface conduit_end_1 conduit end
set_interface_property conduit_end_1 associatedClock clock_sink_1
set_interface_property conduit_end_1 associatedReset reset_sink_1
set_interface_property conduit_end_1 ENABLED true
set_interface_property conduit_end_1 EXPORT_OF ""
set_interface_property conduit_end_1 PORT_NAME_MAP ""
set_interface_property conduit_end_1 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_1 s00_islv_ppwa export Input number_of_ppwas


# 
# connection point clock_sink_1
# 
add_interface clock_sink_1 clock end
set_interface_property clock_sink_1 clockRate 0
set_interface_property clock_sink_1 ENABLED true
set_interface_property clock_sink_1 EXPORT_OF ""
set_interface_property clock_sink_1 PORT_NAME_MAP ""
set_interface_property clock_sink_1 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_1 s00_axi_aclk clk Input 1


# 
# connection point reset_sink_1
# 
add_interface reset_sink_1 reset end
set_interface_property reset_sink_1 associatedClock clock_sink_1
set_interface_property reset_sink_1 synchronousEdges DEASSERT
set_interface_property reset_sink_1 ENABLED true
set_interface_property reset_sink_1 EXPORT_OF ""
set_interface_property reset_sink_1 PORT_NAME_MAP ""
set_interface_property reset_sink_1 SVD_ADDRESS_GROUP ""

add_interface_port reset_sink_1 s00_axi_aresetn reset_n Input 1


# 
# connection point altera_axi4_slave_1
# 
add_interface altera_axi4_slave_1 axi4 end
set_interface_property altera_axi4_slave_1 associatedClock clock_sink_1
set_interface_property altera_axi4_slave_1 associatedReset reset_sink_1
set_interface_property altera_axi4_slave_1 readAcceptanceCapability 1
set_interface_property altera_axi4_slave_1 writeAcceptanceCapability 1
set_interface_property altera_axi4_slave_1 combinedAcceptanceCapability 1
set_interface_property altera_axi4_slave_1 readDataReorderingDepth 1
set_interface_property altera_axi4_slave_1 bridgesToMaster ""
set_interface_property altera_axi4_slave_1 ENABLED true
set_interface_property altera_axi4_slave_1 EXPORT_OF ""
set_interface_property altera_axi4_slave_1 PORT_NAME_MAP ""
set_interface_property altera_axi4_slave_1 SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4_slave_1 s00_axi_awid awid Input c_s00_axi_id_width
add_interface_port altera_axi4_slave_1 s00_axi_awaddr awaddr Input c_s00_axi_addr_width
add_interface_port altera_axi4_slave_1 s00_axi_awlen awlen Input 8
add_interface_port altera_axi4_slave_1 s00_axi_awsize awsize Input 3
add_interface_port altera_axi4_slave_1 s00_axi_awburst awburst Input 2
add_interface_port altera_axi4_slave_1 s00_axi_awvalid awvalid Input 1
add_interface_port altera_axi4_slave_1 s00_axi_awready awready Output 1
add_interface_port altera_axi4_slave_1 s00_axi_wdata wdata Input c_s00_axi_data_width
add_interface_port altera_axi4_slave_1 s00_axi_wstrb wstrb Input c_s00_axi_data_width/8
add_interface_port altera_axi4_slave_1 s00_axi_wlast wlast Input 1
add_interface_port altera_axi4_slave_1 s00_axi_wvalid wvalid Input 1
add_interface_port altera_axi4_slave_1 s00_axi_bid bid Output c_s00_axi_id_width
add_interface_port altera_axi4_slave_1 s00_axi_wready wready Output 1
add_interface_port altera_axi4_slave_1 s00_axi_bresp bresp Output 2
add_interface_port altera_axi4_slave_1 s00_axi_bvalid bvalid Output 1
add_interface_port altera_axi4_slave_1 s00_axi_bready bready Input 1
add_interface_port altera_axi4_slave_1 s00_axi_arid arid Input c_s00_axi_id_width
add_interface_port altera_axi4_slave_1 s00_axi_araddr araddr Input c_s00_axi_addr_width
add_interface_port altera_axi4_slave_1 s00_axi_arlen arlen Input 8
add_interface_port altera_axi4_slave_1 s00_axi_arsize arsize Input 3
add_interface_port altera_axi4_slave_1 s00_axi_arburst arburst Input 2
add_interface_port altera_axi4_slave_1 s00_axi_arvalid arvalid Input 1
add_interface_port altera_axi4_slave_1 s00_axi_arready arready Output 1
add_interface_port altera_axi4_slave_1 s00_axi_rid rid Output c_s00_axi_id_width
add_interface_port altera_axi4_slave_1 s00_axi_rdata rdata Output c_s00_axi_data_width
add_interface_port altera_axi4_slave_1 s00_axi_rresp rresp Output 2
add_interface_port altera_axi4_slave_1 s00_axi_rlast rlast Output 1
add_interface_port altera_axi4_slave_1 s00_axi_rvalid rvalid Output 1
add_interface_port altera_axi4_slave_1 s00_axi_rready rready Input 1

