# TCL File Generated by Component Editor 13.0sp1
# Fri May 27 15:57:48 CEST 2016
# DO NOT MODIFY


# 
# inio_device "IN_IO Device" v1.0
#  2016.05.27.15:57:48
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module inio_device
# 
set_module_property DESCRIPTION ""
set_module_property NAME inio_device
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP fLink/axi/subDevices/IOs
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "IN_IO Device"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL inGPIODevice_v1_0
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file inGPIODevice_v1_0.vhd VHDL PATH vivadoIPPackage/inGPIODevice_1.0/hdl/inGPIODevice_v1_0.vhd TOP_LEVEL_FILE
add_fileset_file inGPIODevice_v1_0_S00_AXI.vhd VHDL PATH vivadoIPPackage/inGPIODevice_1.0/hdl/inGPIODevice_v1_0_S00_AXI.vhd
add_fileset_file flink_definitions.vhd VHDL PATH ../../../../fLink/core/flink_definitions.vhd


# 
# parameters
# 
add_parameter number_of_gpios INTEGER 1
set_parameter_property number_of_gpios DEFAULT_VALUE 1
set_parameter_property number_of_gpios DISPLAY_NAME number_of_gpios
set_parameter_property number_of_gpios TYPE INTEGER
set_parameter_property number_of_gpios UNITS None
set_parameter_property number_of_gpios ALLOWED_RANGES -2147483648:2147483647
set_parameter_property number_of_gpios HDL_PARAMETER true
add_parameter unique_id STD_LOGIC_VECTOR 0
set_parameter_property unique_id DEFAULT_VALUE 0
set_parameter_property unique_id DISPLAY_NAME unique_id
set_parameter_property unique_id TYPE STD_LOGIC_VECTOR
set_parameter_property unique_id UNITS None
set_parameter_property unique_id ALLOWED_RANGES 0:4294967295
set_parameter_property unique_id HDL_PARAMETER true
add_parameter C_S00_AXI_ID_WIDTH INTEGER 1
set_parameter_property C_S00_AXI_ID_WIDTH DEFAULT_VALUE 1
set_parameter_property C_S00_AXI_ID_WIDTH DISPLAY_NAME C_S00_AXI_ID_WIDTH
set_parameter_property C_S00_AXI_ID_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_ID_WIDTH UNITS None
set_parameter_property C_S00_AXI_ID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_ID_WIDTH HDL_PARAMETER true
add_parameter C_S00_AXI_DATA_WIDTH INTEGER 32
set_parameter_property C_S00_AXI_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property C_S00_AXI_DATA_WIDTH DISPLAY_NAME C_S00_AXI_DATA_WIDTH
set_parameter_property C_S00_AXI_DATA_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_DATA_WIDTH UNITS None
set_parameter_property C_S00_AXI_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_DATA_WIDTH HDL_PARAMETER true
add_parameter C_S00_AXI_ADDR_WIDTH INTEGER 12 ""
set_parameter_property C_S00_AXI_ADDR_WIDTH DEFAULT_VALUE 12
set_parameter_property C_S00_AXI_ADDR_WIDTH DISPLAY_NAME C_S00_AXI_ADDR_WIDTH
set_parameter_property C_S00_AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_ADDR_WIDTH UNITS None
set_parameter_property C_S00_AXI_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_ADDR_WIDTH DESCRIPTION ""
set_parameter_property C_S00_AXI_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end islv_gpios export Input number_of_gpios


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink s00_axi_aclk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink s00_axi_aresetn reset_n Input 1


# 
# connection point altera_axi4_slave
# 
add_interface altera_axi4_slave axi4 end
set_interface_property altera_axi4_slave associatedClock clock_sink
set_interface_property altera_axi4_slave associatedReset reset_sink
set_interface_property altera_axi4_slave readAcceptanceCapability 1
set_interface_property altera_axi4_slave writeAcceptanceCapability 1
set_interface_property altera_axi4_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4_slave readDataReorderingDepth 1
set_interface_property altera_axi4_slave bridgesToMaster ""
set_interface_property altera_axi4_slave ENABLED true
set_interface_property altera_axi4_slave EXPORT_OF ""
set_interface_property altera_axi4_slave PORT_NAME_MAP ""
set_interface_property altera_axi4_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4_slave s00_axi_awid awid Input c_s00_axi_id_width
add_interface_port altera_axi4_slave s00_axi_awaddr awaddr Input c_s00_axi_addr_width
add_interface_port altera_axi4_slave s00_axi_awlen awlen Input 8
add_interface_port altera_axi4_slave s00_axi_awsize awsize Input 3
add_interface_port altera_axi4_slave s00_axi_awburst awburst Input 2
add_interface_port altera_axi4_slave s00_axi_awvalid awvalid Input 1
add_interface_port altera_axi4_slave s00_axi_awready awready Output 1
add_interface_port altera_axi4_slave s00_axi_wdata wdata Input c_s00_axi_data_width
add_interface_port altera_axi4_slave s00_axi_wstrb wstrb Input c_s00_axi_data_width/8
add_interface_port altera_axi4_slave s00_axi_wlast wlast Input 1
add_interface_port altera_axi4_slave s00_axi_wvalid wvalid Input 1
add_interface_port altera_axi4_slave s00_axi_wready wready Output 1
add_interface_port altera_axi4_slave s00_axi_bid bid Output c_s00_axi_id_width
add_interface_port altera_axi4_slave s00_axi_bresp bresp Output 2
add_interface_port altera_axi4_slave s00_axi_bvalid bvalid Output 1
add_interface_port altera_axi4_slave s00_axi_bready bready Input 1
add_interface_port altera_axi4_slave s00_axi_arid arid Input c_s00_axi_id_width
add_interface_port altera_axi4_slave s00_axi_araddr araddr Input c_s00_axi_addr_width
add_interface_port altera_axi4_slave s00_axi_arlen arlen Input 8
add_interface_port altera_axi4_slave s00_axi_arsize arsize Input 3
add_interface_port altera_axi4_slave s00_axi_arburst arburst Input 2
add_interface_port altera_axi4_slave s00_axi_arvalid arvalid Input 1
add_interface_port altera_axi4_slave s00_axi_arready arready Output 1
add_interface_port altera_axi4_slave s00_axi_rid rid Output c_s00_axi_id_width
add_interface_port altera_axi4_slave s00_axi_rdata rdata Output c_s00_axi_data_width
add_interface_port altera_axi4_slave s00_axi_rresp rresp Output 2
add_interface_port altera_axi4_slave s00_axi_rlast rlast Output 1
add_interface_port altera_axi4_slave s00_axi_rvalid rvalid Output 1
add_interface_port altera_axi4_slave s00_axi_rready rready Input 1

