# TCL File Generated by Component Editor 13.0sp1
# Tue Apr 19 14:33:22 CEST 2016
# DO NOT MODIFY


# 
# lbp_slave_to_axi_master "LPB Slave to Axi Master" v1.0
#  2016.04.19.14:33:22
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module lbp_slave_to_axi_master
# 
set_module_property DESCRIPTION ""
set_module_property NAME lbp_slave_to_axi_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP fLink/axi/busDevices
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "LPB Slave to Axi Master"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lpb_mpc5200b_to_axi_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mpc5200b_lpb_to_axi_master.vhd VHDL PATH mpc5200b_lpb_to_axi_master.vhd TOP_LEVEL_FILE
add_fileset_file flink_definitions.vhd VHDL PATH ../../../../fLink/core/flink_definitions.vhd


# 
# parameters
# 
add_parameter LPBADDRWIDTH INTEGER 32
set_parameter_property LPBADDRWIDTH DEFAULT_VALUE 32
set_parameter_property LPBADDRWIDTH DISPLAY_NAME LPBADDRWIDTH
set_parameter_property LPBADDRWIDTH TYPE INTEGER
set_parameter_property LPBADDRWIDTH UNITS None
set_parameter_property LPBADDRWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LPBADDRWIDTH HDL_PARAMETER true
add_parameter LPBDATAWIDTH INTEGER 32
set_parameter_property LPBDATAWIDTH DEFAULT_VALUE 32
set_parameter_property LPBDATAWIDTH DISPLAY_NAME LPBDATAWIDTH
set_parameter_property LPBDATAWIDTH TYPE INTEGER
set_parameter_property LPBDATAWIDTH UNITS None
set_parameter_property LPBDATAWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LPBDATAWIDTH HDL_PARAMETER true
add_parameter LPBTSIZEWIDTH INTEGER 3
set_parameter_property LPBTSIZEWIDTH DEFAULT_VALUE 3
set_parameter_property LPBTSIZEWIDTH DISPLAY_NAME LPBTSIZEWIDTH
set_parameter_property LPBTSIZEWIDTH TYPE INTEGER
set_parameter_property LPBTSIZEWIDTH UNITS None
set_parameter_property LPBTSIZEWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LPBTSIZEWIDTH HDL_PARAMETER true
add_parameter LPBCSWIDTH INTEGER 2
set_parameter_property LPBCSWIDTH DEFAULT_VALUE 2
set_parameter_property LPBCSWIDTH DISPLAY_NAME LPBCSWIDTH
set_parameter_property LPBCSWIDTH TYPE INTEGER
set_parameter_property LPBCSWIDTH UNITS None
set_parameter_property LPBCSWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LPBCSWIDTH HDL_PARAMETER true
add_parameter LPBBANKWIDTH INTEGER 2
set_parameter_property LPBBANKWIDTH DEFAULT_VALUE 2
set_parameter_property LPBBANKWIDTH DISPLAY_NAME LPBBANKWIDTH
set_parameter_property LPBBANKWIDTH TYPE INTEGER
set_parameter_property LPBBANKWIDTH UNITS None
set_parameter_property LPBBANKWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LPBBANKWIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point altera_axi4_master
# 
add_interface altera_axi4_master axi4 start
set_interface_property altera_axi4_master associatedClock clock
set_interface_property altera_axi4_master associatedReset reset
set_interface_property altera_axi4_master readIssuingCapability 1
set_interface_property altera_axi4_master writeIssuingCapability 1
set_interface_property altera_axi4_master combinedIssuingCapability 1
set_interface_property altera_axi4_master ENABLED true
set_interface_property altera_axi4_master EXPORT_OF ""
set_interface_property altera_axi4_master PORT_NAME_MAP ""
set_interface_property altera_axi4_master SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4_master axi_awid awid Output 1
add_interface_port altera_axi4_master axi_awaddr awaddr Output 32
add_interface_port altera_axi4_master axi_awlen awlen Output 8
add_interface_port altera_axi4_master axi_awsize awsize Output 3
add_interface_port altera_axi4_master axi_awburst awburst Output 2
add_interface_port altera_axi4_master axi_awvalid awvalid Output 1
add_interface_port altera_axi4_master axi_awready awready Input 1
add_interface_port altera_axi4_master axi_awprot awprot Output 3
add_interface_port altera_axi4_master axi_wdata wdata Output 32
add_interface_port altera_axi4_master axi_wstrb wstrb Output 4
add_interface_port altera_axi4_master axi_wvalid wvalid Output 1
add_interface_port altera_axi4_master axi_wready wready Input 1
add_interface_port altera_axi4_master axi_wlast wlast Output 1
add_interface_port altera_axi4_master axi_araddr araddr Output 32
add_interface_port altera_axi4_master axi_arvalid arvalid Output 1
add_interface_port altera_axi4_master axi_arready arready Input 1
add_interface_port altera_axi4_master axi_arid arid Output 1
add_interface_port altera_axi4_master axi_arlen arlen Output 8
add_interface_port altera_axi4_master axi_arsize arsize Output 3
add_interface_port altera_axi4_master axi_arburst arburst Output 2
add_interface_port altera_axi4_master axi_arprot arprot Output 3
add_interface_port altera_axi4_master axi_rdata rdata Input 32
add_interface_port altera_axi4_master axi_rresp rresp Input 2
add_interface_port altera_axi4_master axi_rvalid rvalid Input 1
add_interface_port altera_axi4_master axi_rready rready Output 1
add_interface_port altera_axi4_master axi_rid rid Input 1
add_interface_port altera_axi4_master axi_rlast rlast Input 1
add_interface_port altera_axi4_master axi_bresp bresp Input 2
add_interface_port altera_axi4_master axi_bvalid bvalid Input 1
add_interface_port altera_axi4_master axi_bready bready Output 1
add_interface_port altera_axi4_master axi_bid bid Input 1


# 
# connection point lpb
# 
add_interface lpb conduit end
set_interface_property lpb associatedClock clock
set_interface_property lpb associatedReset reset
set_interface_property lpb ENABLED true
set_interface_property lpb EXPORT_OF ""
set_interface_property lpb PORT_NAME_MAP ""
set_interface_property lpb SVD_ADDRESS_GROUP ""

add_interface_port lpb lpb_ad export Bidir lpbdatawidth
add_interface_port lpb lpb_cs_n export Input lpbcswidth
add_interface_port lpb lpb_oe_n export Input 1
add_interface_port lpb lpb_ack_n export Output 1
add_interface_port lpb lpb_ale_n export Input 1
add_interface_port lpb lpb_rdwr_n export Input 1
add_interface_port lpb lpb_ts_n export Input 1

