# TCL File Generated by Component Editor 13.0sp1
# Tue Jul 08 16:25:29 CEST 2014
# DO NOT MODIFY


# 
# adc128S102 "adc128S102" v0.1.0
# Tinner Marco 2014.07.08.16:25:29
# Interface Module for an adc128S102
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module adc128S102
# 
set_module_property DESCRIPTION "Interface Module for an adc128S102"
set_module_property NAME adc128S102
set_module_property VERSION 0.1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP fLink
set_module_property AUTHOR "Tinner Marco"
set_module_property DISPLAY_NAME adc128S102
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_adc128S102_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_adc128S102_interface.m.vhd VHDL PATH avalon_adc128S102_interface.m.vhd TOP_LEVEL_FILE
add_fileset_file flink_definitions.vhd VHDL PATH ../../../fLink/core/flink_definitions.vhd
add_fileset_file spi_master.m.vhd VHDL PATH ../../../functionalBlocks/spi_master/src/spi_master.m.vhd
add_fileset_file adc128S102.m.vhd VHDL PATH ../../../functionalBlocks/adc128S102/src/adc128S102.m.vhd


# 
# parameters
# 
add_parameter BASE_CLK INTEGER 33000000
set_parameter_property BASE_CLK DEFAULT_VALUE 33000000
set_parameter_property BASE_CLK DISPLAY_NAME BASE_CLK
set_parameter_property BASE_CLK TYPE INTEGER
set_parameter_property BASE_CLK UNITS None
set_parameter_property BASE_CLK HDL_PARAMETER true
add_parameter SCLK_FREQUENCY INTEGER 10000000
set_parameter_property SCLK_FREQUENCY DEFAULT_VALUE 10000000
set_parameter_property SCLK_FREQUENCY DISPLAY_NAME SCLK_FREQUENCY
set_parameter_property SCLK_FREQUENCY TYPE INTEGER
set_parameter_property SCLK_FREQUENCY UNITS None
set_parameter_property SCLK_FREQUENCY HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 islv_avs_write_data writedata Input 32
add_interface_port avalon_slave_0 oslv_avs_read_data readdata Output 32
add_interface_port avalon_slave_0 islv_avs_address address Input 5
add_interface_port avalon_slave_0 isl_avs_read read Input 1
add_interface_port avalon_slave_0 isl_avs_write write Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink isl_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink isl_reset_n reset_n Input 1


# 
# connection point adc_spi
# 
add_interface adc_spi conduit end
set_interface_property adc_spi associatedClock clock_sink
set_interface_property adc_spi associatedReset reset_sink
set_interface_property adc_spi ENABLED true
set_interface_property adc_spi EXPORT_OF ""
set_interface_property adc_spi PORT_NAME_MAP ""
set_interface_property adc_spi SVD_ADDRESS_GROUP ""

add_interface_port adc_spi osl_sclk export Output 1
add_interface_port adc_spi oslv_Ss export Output 1
add_interface_port adc_spi osl_mosi export Output 1
add_interface_port adc_spi isl_miso export Input 1

