# TCL File Generated by Component Editor 13.0sp1
# Wed May 11 14:52:30 CEST 2016
# DO NOT MODIFY


# 
# loopback_device "Loopback Device" v1.0
#  2016.05.11.14:52:30
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module loopback_device
# 
set_module_property DESCRIPTION ""
set_module_property NAME loopback_device
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP fLink/axi/subDevices
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Loopback Device"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL loopbackDevice_v1_0_S00_AXI
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file flink_definitions.vhd VHDL PATH ../../../../fLink/core/flink_definitions.vhd
add_fileset_file loopbackDevice_v1_0.vhd VHDL PATH vivadoIPPackage/loopbackDevice_1.0/hdl/loopbackDevice_v1_0.vhd
add_fileset_file loopbackDevice_v1_0_S00_AXI.vhd VHDL PATH vivadoIPPackage/loopbackDevice_1.0/hdl/loopbackDevice_v1_0_S00_AXI.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter unique_id STD_LOGIC_VECTOR 0
set_parameter_property unique_id DEFAULT_VALUE 0
set_parameter_property unique_id DISPLAY_NAME unique_id
set_parameter_property unique_id TYPE STD_LOGIC_VECTOR
set_parameter_property unique_id UNITS None
set_parameter_property unique_id ALLOWED_RANGES 0:4294967295
set_parameter_property unique_id HDL_PARAMETER true
add_parameter C_S_AXI_ID_WIDTH INTEGER 1
set_parameter_property C_S_AXI_ID_WIDTH DEFAULT_VALUE 1
set_parameter_property C_S_AXI_ID_WIDTH DISPLAY_NAME C_S_AXI_ID_WIDTH
set_parameter_property C_S_AXI_ID_WIDTH TYPE INTEGER
set_parameter_property C_S_AXI_ID_WIDTH UNITS None
set_parameter_property C_S_AXI_ID_WIDTH HDL_PARAMETER true
add_parameter C_S_AXI_DATA_WIDTH INTEGER 32
set_parameter_property C_S_AXI_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property C_S_AXI_DATA_WIDTH DISPLAY_NAME C_S_AXI_DATA_WIDTH
set_parameter_property C_S_AXI_DATA_WIDTH TYPE INTEGER
set_parameter_property C_S_AXI_DATA_WIDTH UNITS None
set_parameter_property C_S_AXI_DATA_WIDTH HDL_PARAMETER true
add_parameter C_S_AXI_ADDR_WIDTH INTEGER 12
set_parameter_property C_S_AXI_ADDR_WIDTH DEFAULT_VALUE 12
set_parameter_property C_S_AXI_ADDR_WIDTH DISPLAY_NAME C_S_AXI_ADDR_WIDTH
set_parameter_property C_S_AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property C_S_AXI_ADDR_WIDTH UNITS None
set_parameter_property C_S_AXI_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink_1
# 
add_interface clock_sink_1 clock end
set_interface_property clock_sink_1 clockRate 0
set_interface_property clock_sink_1 ENABLED true
set_interface_property clock_sink_1 EXPORT_OF ""
set_interface_property clock_sink_1 PORT_NAME_MAP ""
set_interface_property clock_sink_1 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_1 S_AXI_ACLK clk Input 1


# 
# connection point reset_sink_1
# 
add_interface reset_sink_1 reset end
set_interface_property reset_sink_1 associatedClock clock_sink_1
set_interface_property reset_sink_1 synchronousEdges DEASSERT
set_interface_property reset_sink_1 ENABLED true
set_interface_property reset_sink_1 EXPORT_OF ""
set_interface_property reset_sink_1 PORT_NAME_MAP ""
set_interface_property reset_sink_1 SVD_ADDRESS_GROUP ""

add_interface_port reset_sink_1 S_AXI_ARESETN reset_n Input 1


# 
# connection point altera_axi4_slave
# 
add_interface altera_axi4_slave axi4 end
set_interface_property altera_axi4_slave associatedClock clock_sink_1
set_interface_property altera_axi4_slave associatedReset reset_sink_1
set_interface_property altera_axi4_slave readAcceptanceCapability 1
set_interface_property altera_axi4_slave writeAcceptanceCapability 1
set_interface_property altera_axi4_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4_slave readDataReorderingDepth 1
set_interface_property altera_axi4_slave bridgesToMaster ""
set_interface_property altera_axi4_slave ENABLED true
set_interface_property altera_axi4_slave EXPORT_OF ""
set_interface_property altera_axi4_slave PORT_NAME_MAP ""
set_interface_property altera_axi4_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4_slave S_AXI_AWADDR awaddr Input c_s_axi_addr_width
add_interface_port altera_axi4_slave S_AXI_AWLEN awlen Input 8
add_interface_port altera_axi4_slave S_AXI_AWSIZE awsize Input 3
add_interface_port altera_axi4_slave S_AXI_AWBURST awburst Input 2
add_interface_port altera_axi4_slave S_AXI_AWVALID awvalid Input 1
add_interface_port altera_axi4_slave S_AXI_AWREADY awready Output 1
add_interface_port altera_axi4_slave S_AXI_WDATA wdata Input c_s_axi_data_width
add_interface_port altera_axi4_slave S_AXI_WSTRB wstrb Input c_s_axi_data_width/8
add_interface_port altera_axi4_slave S_AXI_WLAST wlast Input 1
add_interface_port altera_axi4_slave S_AXI_WVALID wvalid Input 1
add_interface_port altera_axi4_slave S_AXI_WREADY wready Output 1
add_interface_port altera_axi4_slave S_AXI_BID bid Output c_s_axi_id_width
add_interface_port altera_axi4_slave S_AXI_BRESP bresp Output 2
add_interface_port altera_axi4_slave S_AXI_BVALID bvalid Output 1
add_interface_port altera_axi4_slave S_AXI_BREADY bready Input 1
add_interface_port altera_axi4_slave S_AXI_ARID arid Input c_s_axi_id_width
add_interface_port altera_axi4_slave S_AXI_ARADDR araddr Input c_s_axi_addr_width
add_interface_port altera_axi4_slave S_AXI_ARLEN arlen Input 8
add_interface_port altera_axi4_slave S_AXI_ARSIZE arsize Input 3
add_interface_port altera_axi4_slave S_AXI_ARBURST arburst Input 2
add_interface_port altera_axi4_slave S_AXI_ARVALID arvalid Input 1
add_interface_port altera_axi4_slave S_AXI_ARREADY arready Output 1
add_interface_port altera_axi4_slave S_AXI_RID rid Output c_s_axi_id_width
add_interface_port altera_axi4_slave S_AXI_RDATA rdata Output c_s_axi_data_width
add_interface_port altera_axi4_slave S_AXI_RRESP rresp Output 2
add_interface_port altera_axi4_slave S_AXI_RLAST rlast Output 1
add_interface_port altera_axi4_slave S_AXI_RVALID rvalid Output 1
add_interface_port altera_axi4_slave S_AXI_RREADY rready Input 1
add_interface_port altera_axi4_slave S_AXI_AWID awid Input c_s_axi_id_width

